version: 2.1
jobs:
  test-emacs-25:
    docker:
      - image: silex/emacs:25-dev
        entrypoint: bash
    <<: *default-steps

  test-emacs-26:
    docker:
      - image: silex/emacs:26-dev
        entrypoint: bash
    <<: *default-steps

  test-emacs-master:
    docker:
      - image: silex/emacs:master-dev
        entrypoint: bash
    <<: *default-steps

# Default actions to perform on each Emacs version
default: &default-steps
  steps:
    - checkout
    - run: apt-get update && apt-get install make
    - run: make elpa
    - run: emacs --version
    - run: git clone https://github.com/Emiller88/doom-emacs-private.git ~/.config/doom
    - run: git clone https://github.com/Emiller88/doom-emacs.git ~/.emacs.d
    - run: cd ~/.emacs.d && YES=1 ./bin/doom install
    - run: emacs


workflows:
  version: 2
  ci-test-matrix:
    jobs:
      - test-emacs-25
      - test-emacs-26
      - test-emacs-master
